In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([1,2,3,4],
             index = ['이익','손실','매출','현금'])
s

이익    1
손실    2
매출    3
현금    4
dtype: int64

In [3]:
x = pd.Series([4,3,5,6],
             index = ['이익','손실','매출','부채'])

In [4]:
list_s = list(s)

In [5]:
list_s

[1, 2, 3, 4]

In [6]:
df = pd.concat([s,x], axis =1)

In [7]:
df

0    1
이익  1.0  4.0
손실  2.0  3.0
매출  3.0  5.0
현금  4.0  NaN
부채  NaN  6.0

In [8]:
s.index

Index(['이익', '손실', '매출', '현금'], dtype='object')

In [9]:
x.index

Index(['이익', '손실', '매출', '부채'], dtype='object')

In [10]:
s.index.difference(x.index)

Index(['현금'], dtype='object')

In [11]:
s.index.union(x.index)

Index(['매출', '부채', '손실', '이익', '현금'], dtype='object')

In [12]:
s.index | x.index

Index(['매출', '부채', '손실', '이익', '현금'], dtype='object')

In [13]:
s.index & x.index

Index(['이익', '손실', '매출'], dtype='object')

In [14]:
s.index ^ x.index

Index(['부채', '현금'], dtype='object')

In [15]:
s = pd.Series([0, 0.25 , 0.5 , 0.75 , 1.0],
             index = ['a','b','c','d','e'])

In [16]:
'a' in s

True

In [17]:
s = pd.Series(['a','b','c','d','e'],
             index = [1,3,5,7,9])

In [18]:
s.reindex(range(10), fill_value =0)

0    0
1    a
2    0
3    b
4    0
5    c
6    0
7    d
8    0
9    e
dtype: object

In [19]:
s.reindex(range(10), method = 'bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

In [20]:
male_tuple = {'서울특별시':720846,
            '부산광역시':404423,
            '인천광역시':947217,
            '대구광역시':427954,
            '대전광역시':471040,
            '광주광역시':455048}
male = pd.Series(male_tuple)
male

서울특별시    720846
부산광역시    404423
인천광역시    947217
대구광역시    427954
대전광역시    471040
광주광역시    455048
dtype: int64

In [21]:
pop_tuple = {'서울특별시':9720846,
            '부산광역시':3404423,
            '인천광역시':2947217,
            '대구광역시':2427954,
            '대전광역시':1471040,
            '광주광역시':1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [22]:
df = pd.DataFrame({'총인구수':population,
             '남자인구수':male_tuple})

In [23]:
df

총인구수   남자인구수
서울특별시  9720846  720846
부산광역시  3404423  404423
인천광역시  2947217  947217
대구광역시  2427954  427954
대전광역시  1471040  471040
광주광역시  1455048  455048

In [24]:
df['여자인구수'] = df['총인구수'] - df['남자인구수']

In [25]:
df

총인구수   남자인구수    여자인구수
서울특별시  9720846  720846  9000000
부산광역시  3404423  404423  3000000
인천광역시  2947217  947217  2000000
대구광역시  2427954  427954  2000000
대전광역시  1471040  471040  1000000
광주광역시  1455048  455048  1000000

In [26]:
df.총인구수

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 총인구수, dtype: int64

In [27]:
df.남자인구수

서울특별시    720846
부산광역시    404423
인천광역시    947217
대구광역시    427954
대전광역시    471040
광주광역시    455048
Name: 남자인구수, dtype: int64

In [28]:
df['남녀비율'] = df.남자인구수 * 100 / df.여자인구수

In [29]:
df

총인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  9000000   8.009400
부산광역시  3404423  404423  3000000  13.480767
인천광역시  2947217  947217  2000000  47.360850
대구광역시  2427954  427954  2000000  21.397700
대전광역시  1471040  471040  1000000  47.104000
광주광역시  1455048  455048  1000000  45.504800

In [30]:
df.values

array([[9.72084600e+06, 7.20846000e+05, 9.00000000e+06, 8.00940000e+00],
       [3.40442300e+06, 4.04423000e+05, 3.00000000e+06, 1.34807667e+01],
       [2.94721700e+06, 9.47217000e+05, 2.00000000e+06, 4.73608500e+01],
       [2.42795400e+06, 4.27954000e+05, 2.00000000e+06, 2.13977000e+01],
       [1.47104000e+06, 4.71040000e+05, 1.00000000e+06, 4.71040000e+01],
       [1.45504800e+06, 4.55048000e+05, 1.00000000e+06, 4.55048000e+01]])

In [32]:
df.T

서울특별시         부산광역시         인천광역시         대구광역시        대전광역시  \
총인구수   9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1471040.000   
남자인구수  7.208460e+05  4.044230e+05  9.472170e+05  4.279540e+05   471040.000   
여자인구수  9.000000e+06  3.000000e+06  2.000000e+06  2.000000e+06  1000000.000   
남녀비율   8.009400e+00  1.348077e+01  4.736085e+01  2.139770e+01       47.104   

              광주광역시  
총인구수   1.455048e+06  
남자인구수  4.550480e+05  
여자인구수  1.000000e+06  
남녀비율   4.550480e+01

In [33]:
df.values[0] # 0 번째index 임 values 하면 행으로 찾는 구나 생각

array([9.720846e+06, 7.208460e+05, 9.000000e+06, 8.009400e+00])

In [35]:
#df.loc[:,'서울특별시':'인천광역시'] # 정렬 안해줘서 오류남

In [36]:
df.sort_index()

총인구수   남자인구수    여자인구수       남녀비율
광주광역시  1455048  455048  1000000  45.504800
대구광역시  2427954  427954  2000000  21.397700
대전광역시  1471040  471040  1000000  47.104000
부산광역시  3404423  404423  3000000  13.480767
서울특별시  9720846  720846  9000000   8.009400
인천광역시  2947217  947217  2000000  47.360850

In [40]:
# df.loc['인천광역시':'광주광역시',1:3]  # 숫자로 인덱싱할 경우 iloc 사용

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [42]:
df.loc[df.총인구수 > 3000000] # 열을 우선적으로 찾음

총인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  9000000   8.009400
부산광역시  3404423  404423  3000000  13.480767

In [ ]:
pop_tuplesidx_tuples
population = pd.DataFrame(pop_tuples, index = idx_tuples)
midx = pd.MultiIndex.from_tuples(idx_tuples)
population.reindex(midx)

In [47]:
pop_tuples = [10312545, 9720846,
             2567910, 3404423,
             2758296, 2947217,
             2511676, 2427954,
             1503664, 1471040,
             1454636, 1455048]
idx_tuples = [('서울특별시', 2010), ('서울특별시',2020),
             ('부산광역시', 2010), ('부산광역시',2020),
             ('인천광역시', 2010), ('인천광역시',2020),
             ('대구광역시', 2010), ('대구광역시',2020),
             ('대전광역시', 2010), ('대전광역시',2020),
             ('광주광역시', 2010), ('광주광역시',2020),]
population = pd.DataFrame(pop_tuple, index=idx_tuples)
midx = pd.MultiIndex.from_tuples(idx_tuples)
population = population.reindex(midx)

In [45]:
male_tuples = [5111259, 4732275,
             1773170, 1668618,
             1390356, 1476813,
             1255245, 1198815,
             753648, 734441,
             721780, 720060]
female_tuples = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1256431, 1229139,
                750016, 736599,
                732856, 734988]

In [48]:
korea_mdf = pd.DataFrame({'총인구수':population,
                         '남자인구수':male_tuples})

ValueError: Shape of passed values is (6, 2), indices imply (12, 2)

In [ ]:
pd.MultiIndex.from_arrays
pd.MultiIndex.from_product

In [49]:
population

서울특별시    부산광역시    인천광역시    대구광역시    대전광역시    광주광역시
서울특별시 2010  9720846  3404423  2947217  2427954  1471040  1455048
      2020  9720846  3404423  2947217  2427954  1471040  1455048
부산광역시 2010  9720846  3404423  2947217  2427954  1471040  1455048
      2020  9720846  3404423  2947217  2427954  1471040  1455048
인천광역시 2010  9720846  3404423  2947217  2427954  1471040  1455048
      2020  9720846  3404423  2947217  2427954  1471040  1455048
대구광역시 2010  9720846  3404423  2947217  2427954  1471040  1455048
      2020  9720846  3404423  2947217  2427954  1471040  1455048
대전광역시 2010  9720846  3404423  2947217  2427954  1471040  1455048
      2020  9720846  3404423  2947217  2427954  1471040  1455048
광주광역시 2010  9720846  3404423  2947217  2427954  1471040  1455048
      2020  9720846  3404423  2947217  2427954  1471040  1455048

In [58]:
population['인천광역시']

서울특별시  2010    2947217
       2020    2947217
부산광역시  2010    2947217
       2020    2947217
인천광역시  2010    2947217
       2020    2947217
대구광역시  2010    2947217
       2020    2947217
대전광역시  2010    2947217
       2020    2947217
광주광역시  2010    2947217
       2020    2947217
Name: 인천광역시, dtype: int64

In [56]:
seoul_list = list(population['서울특별시'])
seoul_list

[9720846,
 9720846,
 9720846,
 9720846,
 9720846,
 9720846,
 9720846,
 9720846,
 9720846,
 9720846,
 9720846,
 9720846]

In [ ]:
# 시리즈는 행 데이터프레임은 열이 기준이다. 멀티 인덱스에서는 행으로 검색 가능

In [ ]:
# unstack or reset_index 에서의 param 인 level 은 멀티인덱스는 인덱스 기준.

In [59]:
# 멀티인덱스 행 검색시 sort_index() 필요

In [60]:
a = np.random.randint(1,10, size=(3,3))
a

array([[5, 2, 2],
       [6, 5, 1],
       [9, 6, 2]])

In [62]:
a / a[0]

array([[1. , 1. , 1. ],
       [1.2, 2.5, 0.5],
       [1.8, 3. , 1. ]])

In [64]:
df = pd.DataFrame(a , columns=list('ABC'))
df

A  B  C
0  1  1  2
1  2  7  9
2  1  2  8

In [66]:
df.truediv(df.iloc[0])

A    B    C
0  1.0  1.0  1.0
1  2.0  7.0  4.5
2  1.0  2.0  4.0

In [68]:
df / df.iloc[0]

A    B    C
0  1.0  1.0  1.0
1  2.0  7.0  4.5
2  1.0  2.0  4.0

In [72]:
nrows, ncols = 10000 ,100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [75]:
pd.eval('df1 - df2 +df2 - df3 / df3 ** df4 -df2')

0         1         2         3         4         5         6   \
0     0.275050 -0.411342 -0.635264 -0.813656 -0.699304  0.023741 -0.553741   
1    -1.104590 -1.117197  0.422818 -0.890008 -1.002853  0.109782 -0.589420   
2    -0.409888 -1.168151 -0.700093 -1.330508 -0.358400 -0.975218 -0.121880   
3    -0.910855 -0.815799 -1.795087 -0.249921 -0.659888 -0.913924 -1.235688   
4    -0.381328 -0.774296 -0.556478 -1.821066 -1.392632 -1.485317 -1.289933   
...        ...       ...       ...       ...       ...       ...       ...   
9995 -0.274403 -1.066183 -0.416792 -0.723173 -0.189830 -0.059897 -1.428595   
9996 -0.251911 -1.221082 -0.753761 -0.866861 -0.474774 -0.603689 -0.843519   
9997 -0.885579 -0.104465 -0.555215  0.322355 -1.500712 -0.827022 -1.047521   
9998 -1.071113 -1.722478 -0.848348 -0.752541  0.001301 -1.253264 -0.257500   
9999 -0.598520 -0.970151 -0.868020 -0.328781 -1.085052 -1.346567 -0.228926   

            7         8         9   ...        90        91        92  \
0    -0.998849 -1.325931 -0.438560  ... -0.796777  0.100841  0.184200   
1    -0.891666 -1.104953 -0.273772  ... -0.595108  0.304469 -1.566772   
2    -0.896665 -0.563002 -0.337774  ... -0.129464 -1.115137 -1.482565   
3    -0.949323 -1.360220 -1.383450  ... -0.146013  0.095233 -1.539736   
4     0.706638 -0.435445 -0.872415  ... -0.214318 -0.479861 -0.825976   
...        ...       ...       ...  ...       ...       ...       ...   
9995 -0.841002 -0.602606 -0.008773  ... -0.441967 -1.118581  0.659808   
9996 -0.979894 -1.338051 -0.997624  ... -1.415807 -0.974948 -0.884728   
9997 -0.634438 -0.962600 -0.599813  ... -1.454562 -0.693687 -0.395854   
9998 -0.943180 -1.030127 -1.581312  ... -0.283532 -1.140474 -0.911156   
9999  0.059181 -0.216768 -0.488237  ... -0.249852  0.014397 -0.999779   

            93        94        95        96        97        98        99  
0    -0.723496 -0.877407 -0.439845  0.407013 -0.710742 -0.057006 -1.100656  
1    -1.178255 -0.599924  0.217800 -1.699540 -0.761928  0.180733 -0.568643  
2    -1.128915 -0.016563 -0.446137 -1.386842 -0.406887 -0.417684 -0.748301  
3    -0.463258 -0.223329  0.008725  0.370846 -0.198714 -0.715929 -1.478955  
4    -1.364218 -0.651893 -0.196966 -0.553147 -1.473450 -0.356427 -0.972138  
...        ...       ...       ...       ...       ...       ...       ...  
9995 -0.861891 -0.270262 -1.038586 -0.867348  0.198082 -0.277680 -0.639926  
9996 -1.119406 -0.562808 -0.809252 -0.475152 -0.989706 -0.451236 -1.394408  
9997 -1.075472 -1.607736 -0.426253 -0.845518 -0.447241 -1.569227 -0.961876  
9998 -1.512926 -0.575720 -0.740675 -0.468665 -0.993775 -0.057575 -0.486316  
9999 -0.251008 -0.397281 -1.204940 -0.975295 -1.066283 -1.361137  0.187769  

[10000 rows x 100 columns]

In [80]:
df1

0         1         2         3         4         5         6   \
0     0.801053  0.021106  0.282067  0.244632  0.654009  0.554041  0.856829   
1     0.516428  0.258316  0.871813  0.098204  0.764704  0.631331  0.395052   
2     0.553836  0.639795  0.153869  0.311605  0.999557  0.560511  0.851226   
3     0.256976  0.639467  0.071427  0.964534  0.349950  0.818607  0.297289   
4     0.244068  0.702309  0.938456  0.118490  0.151315  0.233962  0.540175   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.789815  0.821299  0.859978  0.771294  0.674834  0.597968  0.221222   
9996  0.390862  0.616049  0.562233  0.352647  0.494676  0.265732  0.862487   
9997  0.195312  0.760406  0.630188  0.733711  0.059946  0.815208  0.792979   
9998  0.829652  0.076824  0.129524  0.514068  0.821094  0.377733  0.649435   
9999  0.520253  0.446754  0.336841  0.964609  0.283472  0.163041  0.784308   

            7         8         9   ...        90        91        92  \
0     0.115692  0.394008  0.897053  ...  0.094331  0.983370  0.961876   
1     0.241309  0.416495  0.754215  ...  0.437675  0.788335  0.031135   
2     0.433464  0.156519  0.816234  ...  0.586549  0.859610  0.248032   
3     0.025986  0.041308  0.459512  ...  0.710597  0.970216  0.274401   
4     0.912602  0.498198  0.066371  ...  0.605963  0.521375  0.311838   
...        ...       ...       ...  ...       ...       ...       ...   
9995  0.700040  0.890226  0.928932  ...  0.289115  0.536683  0.823188   
9996  0.343820  0.012448  0.205102  ...  0.307614  0.288262  0.843467   
9997  0.807292  0.916958  0.880796  ...  0.146823  0.413741  0.241178   
9998  0.857007  0.771172  0.128272  ...  0.790936  0.066601  0.277218   
9999  0.590533  0.900020  0.584286  ...  0.470263  0.459980  0.099557   

            93        94        95        96        97        98        99  
0     0.042884  0.124190  0.609703  0.725669  0.290185  0.135923  0.420752  
1     0.108568  0.284892  0.661924  0.226656  0.615849  0.836447  0.600888  
2     0.201945  0.976617  0.468212  0.121864  0.607781  0.169028  0.263443  
3     0.562506  0.428647  0.951977  0.875998  0.542294  0.353000  0.431379  
4     0.375353  0.962934  0.741364  0.414355  0.242962  0.701343  0.689736  
...        ...       ...       ...       ...       ...       ...       ...  
9995  0.526340  0.648373  0.072656  0.613051  0.960720  0.857706  0.393413  
9996  0.454309  0.775582  0.715121  0.669598  0.590660  0.810066  0.134355  
9997  0.612862  0.115427  0.284721  0.906872  0.847545  0.006555  0.335977  
9998  0.053535  0.670119  0.893709  0.709281  0.252066  0.990588  0.706791  
9999  0.430850  0.683901  0.540281  0.251330  0.128404  0.144073  0.640129  

[10000 rows x 100 columns]

1