# [Pandas 한번에 제대로 배우기](https://www.youtube.com/watch?v=lG8pEwvYwCw&t=5887s)




---



In [1]:
import pandas as pd
import numpy as np

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
             index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [3]:
s['a']

0.0

In [4]:
s['c']

0.5

In [5]:
'b' in s

True

In [6]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
             index = ['2','4','6','8','10'])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [7]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [8]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [10]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [11]:
pop_tuple = {'서울특별시':9720846,
            '부산광역시':3404423,
            '인천광역시':2947217,
            '대구광역시':2427954,
            '대전광역시':1471040,
            '광주광역시':1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [12]:
population['서울특별시']

9720846

In [13]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [14]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4,'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [15]:
pd.DataFrame(np.random.rand(5,5),
            columns = ['A','B','C','D','E'],
             index = [1,2,3,4,5])

A         B         C         D         E
1  0.352856  0.010354  0.078034  0.041395  0.481295
2  0.031349  0.716951  0.113347  0.947563  0.025172
3  0.486019  0.645221  0.155541  0.279900  0.591850
4  0.126976  0.762958  0.553609  0.853692  0.750683
5  0.612897  0.059653  0.201826  0.732129  0.910549

In [16]:
male_tuple = {'서울특별시':720846,
            '부산광역시':404423,
            '인천광역시':947217,
            '대구광역시':427954,
            '대전광역시':471040,
            '광주광역시':455048}
male = pd.Series(male_tuple)
male

서울특별시    720846
부산광역시    404423
인천광역시    947217
대구광역시    427954
대전광역시    471040
광주광역시    455048
dtype: int64

In [17]:
female_tuple = {'서울특별시':1720846,
            '부산광역시':1404423,
            '인천광역시':1947217,
            '대구광역시':4227954,
            '대전광역시':1471040,
            '광주광역시':1455048}
female = pd.Series(female_tuple)
female

서울특별시    1720846
부산광역시    1404423
인천광역시    1947217
대구광역시    4227954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [18]:
korea_df = pd.DataFrame({'인구수':population,
              '남자인구수':male,
              '여자인구수':female})

In [19]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [20]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [21]:
korea_df['여자인구수']

서울특별시    1720846
부산광역시    1404423
인천광역시    1947217
대구광역시    4227954
대전광역시    1471040
광주광역시    1455048
Name: 여자인구수, dtype: int64

### Index 객체


In [22]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [23]:
idx[1]

4

In [24]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [25]:
idx[-1::]

Int64Index([10], dtype='int64')

In [26]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [27]:
print(idx)
print(idx.size)
print(idx.ndim)
print(idx.shape)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
1
(5,)
int64


#### Index 연산

In [28]:
idx1 = pd.Index([1,2,3,4,5])
idx2 = pd.Index([4,5,6,7,8])

print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2 )
print(idx1.delete(0))
print(idx1.drop(1))


Int64Index([1, 2, 3, 4, 5, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 3], dtype='int64')
Int64Index([-3, -3, -3, -3, -3], dtype='int64')
Int64Index([4, 5], dtype='int64')
Int64Index([4, 5], dtype='int64')
Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 3, 4, 5], dtype='int64')
Int64Index([2, 3, 4, 5], dtype='int64')
Int64Index([1, 2, 3, 6, 7, 8], dtype='int64')


## 인덱싱(Indexing)

In [29]:
s = pd.Series([0, 0.25 , 0.5 , 0.75 , 1.0],
             index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [30]:
s['b']

0.25

In [31]:
'b' in s

True

In [32]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [33]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [34]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [35]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [36]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [37]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [38]:
s[['a','c','d']]

a    0.00
c    0.50
d    0.75
dtype: float64

### Series 인덱싱

In [39]:
s = pd.Series(['a','b','c','d','e'],
             index = [1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [40]:
s[1]

'a'

In [41]:
s[2:4]

5    c
7    d
dtype: object

In [42]:
s.iloc[1]

'b'

In [43]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [44]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [45]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [46]:
korea_df

인구수   남자인구수    여자인구수
서울특별시  9720846  720846  1720846
부산광역시  3404423  404423  1404423
인천광역시  2947217  947217  1947217
대구광역시  2427954  427954  4227954
대전광역시  1471040  471040  1471040
광주광역시  1455048  455048  1455048

In [47]:
korea_df['남자인구수']

서울특별시    720846
부산광역시    404423
인천광역시    947217
대구광역시    427954
대전광역시    471040
광주광역시    455048
Name: 남자인구수, dtype: int64

In [48]:
korea_df.남자인구수

서울특별시    720846
부산광역시    404423
인천광역시    947217
대구광역시    427954
대전광역시    471040
광주광역시    455048
Name: 남자인구수, dtype: int64

In [49]:
korea_df.여자인구수

서울특별시    1720846
부산광역시    1404423
인천광역시    1947217
대구광역시    4227954
대전광역시    1471040
광주광역시    1455048
Name: 여자인구수, dtype: int64

In [50]:
korea_df['남녀비율'] = (korea_df.남자인구수*100 / korea_df.여자인구수)

In [51]:
korea_df

인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  1720846  41.889048
부산광역시  3404423  404423  1404423  28.796381
인천광역시  2947217  947217  1947217  48.644655
대구광역시  2427954  427954  4227954  10.122012
대전광역시  1471040  471040  1471040  32.020883
광주광역시  1455048  455048  1455048  31.273745

In [52]:
korea_df.values

array([[9.72084600e+06, 7.20846000e+05, 1.72084600e+06, 4.18890476e+01],
       [3.40442300e+06, 4.04423000e+05, 1.40442300e+06, 2.87963811e+01],
       [2.94721700e+06, 9.47217000e+05, 1.94721700e+06, 4.86446554e+01],
       [2.42795400e+06, 4.27954000e+05, 4.22795400e+06, 1.01220117e+01],
       [1.47104000e+06, 4.71040000e+05, 1.47104000e+06, 3.20208832e+01],
       [1.45504800e+06, 4.55048000e+05, 1.45504800e+06, 3.12737449e+01]])

In [53]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  7.208460e+05  4.044230e+05  9.472170e+05  4.279540e+05  4.710400e+05   
여자인구수  1.720846e+06  1.404423e+06  1.947217e+06  4.227954e+06  1.471040e+06   
남녀비율   4.188905e+01  2.879638e+01  4.864466e+01  1.012201e+01  3.202088e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  4.550480e+05  
여자인구수  1.455048e+06  
남녀비율   3.127374e+01

In [54]:
korea_df.values[0] # 서울특별시만

array([9.72084600e+06, 7.20846000e+05, 1.72084600e+06, 4.18890476e+01])

In [55]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [56]:
korea_df.loc[:'인천광역시',:'남자인구수']

인구수   남자인구수
서울특별시  9720846  720846
부산광역시  3404423  404423
인천광역시  2947217  947217

In [57]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  1720846  41.889048
부산광역시  3404423  404423  1404423  28.796381
인천광역시  2947217  947217  1947217  48.644655
대구광역시  2427954  427954  4227954  10.122012
대전광역시  1471040  471040  1471040  32.020883
광주광역시  1455048  455048  1455048  31.273745

In [58]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수    여자인구수       남녀비율
대전광역시  1471040  471040  1471040  32.020883
광주광역시  1455048  455048  1455048  31.273745

In [59]:
korea_df.loc[(korea_df.인구수 >= 2500000)]

인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  1720846  41.889048
부산광역시  3404423  404423  1404423  28.796381
인천광역시  2947217  947217  1947217  48.644655

In [60]:
korea_df.loc[korea_df.남녀비율>100]

Empty DataFrame
Columns: [인구수, 남자인구수, 여자인구수, 남녀비율]
Index: []

In [61]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남녀비율 < 100)]

인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  1720846  41.889048
부산광역시  3404423  404423  1404423  28.796381
인천광역시  2947217  947217  1947217  48.644655

In [62]:
korea_df.iloc[:3,:2]

인구수   남자인구수
서울특별시  9720846  720846
부산광역시  3404423  404423
인천광역시  2947217  947217

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [63]:
idx_tuples = [('서울특별시', 2010), ('서울특별시',2020),
             ('부산광역시', 2010), ('부산광역시',2020),
             ('인천광역시', 2010), ('인천광역시',2020),
             ('대구광역시', 2010), ('대구광역시',2020),
             ('대전광역시', 2010), ('대전광역시',2020),
             ('광주광역시', 2010), ('광주광역시',2020),]

In [64]:
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [65]:
pop_tuples = [10312545, 9720846,
             2567910, 3404423,
             2758296, 2947217,
             2511676, 2427954,
             1503664, 1471040,
             1454636, 1455048]
population = pd.Series(pop_tuples, index = idx_tuples)

In [66]:
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [67]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [68]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [69]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [70]:
population['대전광역시',:]

2010    1503664
2020    1471040
dtype: int64

In [71]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [72]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [73]:
male_tuples = [5111259, 4732275,
             1773170, 1668618,
             1390356, 1476813,
             1255245, 1198815,
             753648, 734441,
             721780, 720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [74]:
korea_mdf = pd.DataFrame({'총인구수':population,
                         '남자인구수':male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [75]:
female_tuples = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1256431, 1229139,
                750016, 736599,
                732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [76]:
korea_mdf = pd.DataFrame({'총인구수':population,
                         '남자인구수':male_tuples,
                         '여자인구수':female_tuples,})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [77]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [78]:
korea_mdf = pd.DataFrame({'총인구수':population,
                         '남자인구수':male_tuples,
                         '여자인구수':female_tuples,
                         '남녀비율':ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [79]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

#### 다중 인덱스 생성

In [80]:
df = pd.DataFrame(np.random.rand(6,3),
                 index = [['a','a','b','b','c','c'], [1,2,1,2,1,2,]],
                 columns = ['c1','c2','c3'])
df

c1        c2        c3
a 1  0.205520  0.665843  0.368158
  2  0.880471  0.245758  0.475968
b 1  0.143348  0.988347  0.231359
  2  0.464022  0.477166  0.519976
c 1  0.383175  0.443037  0.984748
  2  0.454793  0.575492  0.928144

In [81]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'], [1,2,1,2,1,2,]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [82]:
pd.MultiIndex.from_product([['a','b','c'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [83]:
pd.MultiIndex.from_product

<bound method MultiIndex.from_product of <class 'pandas.core.indexes.multi.MultiIndex'>>

In [84]:
pd.MultiIndex(levels=[['a','b','c'], [1,2]],
             codes = [[0,0,1,1,2,2], [0,1,0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [85]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [292]:
idx = pd.MultiIndex.from_product([['a','b','c'],[1,2]],
                                names= ['name1','name2'])
cols = pd.MultiIndex.from_product([['c1','c2','c3'], [1,2]],
                                 names = ['col_name1','col_name2'])
data = np.round(np.random.randn(6, 6,),3)
mdf = pd.DataFrame(data, index = idx, columns = cols)
mdf

col_name1       c1            c2            c3       
col_name2        1      2      1      2      1      2
name1 name2                                          
a     1      0.631  1.470 -0.567  0.216 -1.393  1.257
      2      0.590 -0.522  0.456  1.090  0.376  0.067
b     1      0.228 -1.103  1.963 -0.617 -1.319 -1.451
      2     -1.207  0.116 -1.173 -0.469  0.744  1.399
c     1     -0.219  1.611  1.615  0.365  0.466 -1.295
      2     -0.890  1.451 -0.126 -0.470  0.327 -1.167

#### 인덱싱 및 슬라이싱

In [293]:
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [87]:
population['인천광역시', 2010]

2758296

In [88]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [89]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [90]:
population[['대구광역시','부산광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
부산광역시  2010    2567910
       2020    3404423
dtype: int64

In [300]:
mdf

col_name1       c1            c2            c3       
col_name2        1      2      1      2      1      2
name1 name2                                          
a     1      0.631  1.470 -0.567  0.216 -1.393  1.257
      2      0.590 -0.522  0.456  1.090  0.376  0.067
b     1      0.228 -1.103  1.963 -0.617 -1.319 -1.451
      2     -1.207  0.116 -1.173 -0.469  0.744  1.399
c     1     -0.219  1.611  1.615  0.365  0.466 -1.295
      2     -0.890  1.451 -0.126 -0.470  0.327 -1.167

In [301]:
mdf['c2',1]

name1  name2
a      1       -0.567
       2        0.456
b      1        1.963
       2       -1.173
c      1        1.615
       2       -0.126
Name: (c2, 1), dtype: float64

In [93]:
mdf.iloc[:3,:4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -0.47 -0.03 -1.33  0.33
      2     -0.25 -0.61 -0.68 -0.78
b     1     -1.44 -1.03  1.43 -0.86

In [298]:
mdf.loc[:, ('c1',1)]

name1  name2
a      1        0.631
       2        0.590
b      1        0.228
       2       -1.207
c      1       -0.219
       2       -0.890
Name: (c1, 1), dtype: float64

In [95]:
idx_slice = pd.IndexSlice

In [96]:
mdf.loc[idx_slice[:,2], idx_slice[:,2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2     -0.61 -0.78  0.37
b     2     -2.77  0.00 -0.73
c     2      1.32  1.52 -2.13

#### 다중 인덱스 재정렬

In [97]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [98]:
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [99]:
# korea_mdf['서울특별시':'인천광역시'] # 정렬을 해줘야 함.
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [304]:
korea_mdf['총인구수']

행정구역   년도  
광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
Name: 총인구수, dtype: int64

In [295]:
korea_mdf['광주광역시':'대구광역시']

총인구수    남자인구수    여자인구수       남녀비율
행정구역  년도                                        
광주광역시 2010  1454636   721780   732856  98.488653
      2020  1455048   720060   734988  97.968946
대구광역시 2010  2511676  1255245  1256431  99.905606
      2020  2427954  1198815  1229139  97.532907

In [101]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남녀비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [102]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남녀비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [103]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남녀비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남녀비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남녀비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남녀비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남녀비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남녀비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남녀비율     9.879815e+01
 

In [104]:
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [105]:
idx_flat = korea_mdf.reset_index()

In [106]:
idx_flat # flat한 형태로 변경됨

행정구역    년도      총인구수    남자인구수    여자인구수        남녀비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [107]:
idx_flat = korea_mdf.reset_index(level = (0 ,1))

In [108]:
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남녀비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [109]:
idx_flat.set_index(['행정구역','년도'])

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [110]:
s = pd.Series(np.random.randint(0, 10,5))
s

0    9
1    8
2    2
3    3
4    0
dtype: int32

In [111]:
df = pd.DataFrame(np.random.randint(0,10, (3,3)),
                  columns=['A','B','C'])
df

A  B  C
0  8  8  1
1  0  4  5
2  9  3  4

In [112]:
np.exp(s)

0    8103.083928
1    2980.957987
2       7.389056
3      20.085537
4       1.000000
dtype: float64

In [113]:
np.cos(df*np.pi/4)

A         B         C
0  1.000000  1.000000  0.707107
1  1.000000 -1.000000 -0.707107
2  0.707107 -0.707107 -1.000000

In [114]:
s1 = pd.Series([1,3,5,7,9], index = [0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10], index = [1,2,3,4,5])
s1+s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [115]:
s1.add(s2, fill_value = 0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [306]:
df1 = pd.DataFrame(np.random.randint(0,20,(3,3)),
                  columns=list('ACD'))
df1

8.222222222222221

In [117]:
df2 = pd.DataFrame(np.random.randint(0,20,(5,5)),
                  columns=list('BAECD'))
df2

B   A   E   C   D
0  14  15   1  10  11
1  13  15   3   9  17
2   1  17  17  19  16
3  19   1   6   5   8
4  10   2   4  11  13

In [118]:
df1 + df2 

A   B     C     D   E
0  33.0 NaN  18.0  26.0 NaN
1  17.0 NaN  25.0  20.0 NaN
2  26.0 NaN  19.0  16.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [119]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value = fvalue)

A          B          C          D          E
0  33.000000  21.888889  18.000000  26.000000   8.888889
1  17.000000  20.888889  25.000000  20.000000  10.888889
2  26.000000   8.888889  19.000000  16.000000  24.888889
3   8.888889  26.888889  12.888889  15.888889  13.888889
4   9.888889  17.888889  18.888889  20.888889  11.888889

### 연산자 범용 함수


#### add()

In [120]:
a = np.random.randint(1,10, size=(3,3))
a

array([[7, 3, 5],
       [5, 9, 4],
       [9, 2, 4]])

In [121]:
a + a[0]

array([[14,  6, 10],
       [12, 12,  9],
       [16,  5,  9]])

In [122]:
df = pd.DataFrame(a , columns=list('ABC'))
df

A  B  C
0  7  3  5
1  5  9  4
2  9  2  4

In [123]:
df+df.iloc[0]

A   B   C
0  14   6  10
1  12  12   9
2  16   5   9

In [124]:
df.add(df.iloc[0])

A   B   C
0  14   6  10
1  12  12   9
2  16   5   9

#### sub() / subtract()

In [125]:
a

array([[7, 3, 5],
       [5, 9, 4],
       [9, 2, 4]])

In [126]:
a-a[0]

array([[ 0,  0,  0],
       [-2,  6, -1],
       [ 2, -1, -1]])

In [127]:
df

A  B  C
0  7  3  5
1  5  9  4
2  9  2  4

In [128]:
df-df.iloc[0]

A  B  C
0  0  0  0
1 -2  6 -1
2  2 -1 -1

In [129]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1 -2  6 -1
2  2 -1 -1

In [130]:
df.subtract(df['B'], axis=0)

A  B  C
0  4  0  2
1 -4  0 -5
2  7  0  2

#### mul() / multply()




In [131]:
a

array([[7, 3, 5],
       [5, 9, 4],
       [9, 2, 4]])

In [132]:
a*a[1]

array([[35, 27, 20],
       [25, 81, 16],
       [45, 18, 16]])

In [133]:
df

A  B  C
0  7  3  5
1  5  9  4
2  9  2  4

In [134]:
df*df.iloc[1]

A   B   C
0  35  27  20
1  25  81  16
2  45  18  16

In [135]:
df.mul(df.iloc[1])

A   B   C
0  35  27  20
1  25  81  16
2  45  18  16

In [136]:
df.multiply(df.iloc[1])

A   B   C
0  35  27  20
1  25  81  16
2  45  18  16

#### truediv() /  div() / divide() / floordiv()

In [137]:
a

array([[7, 3, 5],
       [5, 9, 4],
       [9, 2, 4]])

In [138]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.71428571, 3.        , 0.8       ],
       [1.28571429, 0.66666667, 0.8       ]])

In [139]:
df

A  B  C
0  7  3  5
1  5  9  4
2  9  2  4

In [140]:
df / df.iloc[0]

A         B    C
0  1.000000  1.000000  1.0
1  0.714286  3.000000  0.8
2  1.285714  0.666667  0.8

In [141]:
df.truediv(df.iloc[0])

A         B    C
0  1.000000  1.000000  1.0
1  0.714286  3.000000  0.8
2  1.285714  0.666667  0.8

In [142]:
df.div(df.iloc[0])

A         B    C
0  1.000000  1.000000  1.0
1  0.714286  3.000000  0.8
2  1.285714  0.666667  0.8

In [143]:
a // a[0]

array([[1, 1, 1],
       [0, 3, 0],
       [1, 0, 0]], dtype=int32)

In [144]:
df.floordiv(df.iloc[1])

A  B  C
0  1  0  1
1  1  1  1
2  1  0  1

#### mod() 나머지

In [145]:
a % a[0]

array([[0, 0, 0],
       [5, 0, 4],
       [2, 2, 4]], dtype=int32)

In [146]:
df

A  B  C
0  7  3  5
1  5  9  4
2  9  2  4

In [147]:
df.mod(df.iloc[1])

A  B  C
0  2  3  1
1  0  0  0
2  4  2  0

#### pow()

In [148]:
a ** a[0]

array([[ 823543,      27,    3125],
       [  78125,     729,    1024],
       [4782969,       8,    1024]], dtype=int32)

In [149]:
df

A  B  C
0  7  3  5
1  5  9  4
2  9  2  4

In [150]:
df.pow(df.iloc[1])

A          B    C
0  16807      19683  625
1   3125  387420489  256
2  59049        512  256

In [151]:
df

A  B  C
0  7  3  5
1  5  9  4
2  9  2  4

In [152]:
row = df.iloc[0, ::2]
row

A    7
C    5
Name: 0, dtype: int32

In [153]:
df - row

A   B    C
0  0.0 NaN  0.0
1 -2.0 NaN -1.0
2  2.0 NaN -1.0

### 정렬(Sort)

In [154]:
s = pd.Series(range(5), index=['A','B','C','D','E'])
s

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [155]:
s.sort_values()

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [156]:
df = pd.DataFrame(np.random.randint(0, 10 ,(4,4)),
                 index=[2,4,1,3],
                 columns = list('BDAC'))
df

B  D  A  C
2  2  8  4  9
4  6  0  5  4
1  6  1  7  7
3  6  3  7  0

In [157]:
df.sort_index()

B  D  A  C
1  6  1  7  7
2  2  8  4  9
3  6  3  7  0
4  6  0  5  4

In [158]:
df.sort_index(axis =1)

A  B  C  D
2  4  2  9  8
4  5  6  4  0
1  7  6  7  1
3  7  6  0  3

In [159]:
df.sort_values(by='A')

B  D  A  C
2  2  8  4  9
4  6  0  5  4
1  6  1  7  7
3  6  3  7  0

In [160]:
df.sort_values(by=['A','C'])

B  D  A  C
2  2  8  4  9
4  6  0  5  4
3  6  3  7  0
1  6  1  7  7

### 순위(Ranking)


In [161]:
s = pd.Series([1,3,32,45,4.2,4,234,43,23,343,43,4,43,33])
s

0       1.0
1       3.0
2      32.0
3      45.0
4       4.2
5       4.0
6     234.0
7      43.0
8      23.0
9     343.0
10     43.0
11      4.0
12     43.0
13     33.0
dtype: float64

In [162]:
s.rank()

0      1.0
1      2.0
2      7.0
3     12.0
4      5.0
5      3.5
6     13.0
7     10.0
8      6.0
9     14.0
10    10.0
11     3.5
12    10.0
13     8.0
dtype: float64

In [163]:
s.rank(method='first')

0      1.0
1      2.0
2      7.0
3     12.0
4      5.0
5      3.0
6     13.0
7      9.0
8      6.0
9     14.0
10    10.0
11     4.0
12    11.0
13     8.0
dtype: float64

In [164]:
s.rank(method='max')

0      1.0
1      2.0
2      7.0
3     12.0
4      5.0
5      4.0
6     13.0
7     11.0
8      6.0
9     14.0
10    11.0
11     4.0
12    11.0
13     8.0
dtype: float64

### 고성능 연산

In [165]:
nrows, ncols = 100000, 100
df1, df2, df3 , df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [166]:
%timeit df1 + df2 + df3 +df4

102 ms ± 605 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [167]:
%timeit pd.eval('df1+df2+df3+df4')

43.3 ms ± 445 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [168]:
%timeit df1 * df2 / (-df3 * df4)

133 ms ± 1.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [169]:
%timeit pd.eval('df1 * df2 / (-df3 * df4)')

44.7 ms ± 639 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [170]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & df3 != df4')

27 ms ± 730 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [171]:
df = pd.DataFrame(np.random.rand(1000000, 5),
                 columns = ['A','B','C','D','E'])

In [172]:
%timeit pd.eval('df.A + df.B / df.C -df.D*df.E')

7 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [173]:
%time df.eval('A + B / C - D * E')

Wall time: 17.5 ms


0         1.156176
1         0.137180
2         0.612659
3         0.484446
4         1.659934
            ...   
999995    9.655322
999996    1.418406
999997    3.027517
999998    4.254516
999999    1.525198
Length: 1000000, dtype: float64

In [174]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.977619  0.356420  0.789086  0.562096  0.485914  1.156176
1  0.045590  0.059767  0.321974  0.698530  0.134622  0.137180
2  0.739505  0.006820  0.599170  0.983149  0.140597  0.612659
3  0.619298  0.024268  0.560397  0.245315  0.726236  0.484446
4  0.572136  0.775192  0.560307  0.973297  0.303829  1.659934

In [175]:
col_mean = df.mean(1)
df['A'] + col_mean

0         1.698838
1         0.278533
2         1.253155
3         1.062624
4         1.379585
            ...   
999995    2.899524
999996    1.753304
999997    1.500179
999998    2.106966
999999    0.647303
Length: 1000000, dtype: float64

In [176]:
df.eval('A + @col_mean') # 외부 값 가져옴

0         1.698838
1         0.278533
2         1.253155
3         1.062624
4         1.379585
            ...   
999995    2.899524
999996    1.753304
999997    1.500179
999998    2.106966
999999    0.647303
Length: 1000000, dtype: float64

In [177]:
df[(df.A < 0.5) & (df.B > 0.7)]

A         B         C         D         E         R
5       0.440921  0.838153  0.248619  0.202795  0.156731  3.780372
8       0.466091  0.993029  0.383327  0.956249  0.387757  2.685855
18      0.466075  0.805493  0.217403  0.552942  0.440928  3.927339
35      0.411488  0.706803  0.459651  0.805474  0.650193  1.425469
44      0.113028  0.903721  0.461744  0.981137  0.169687  1.903733
...          ...       ...       ...       ...       ...       ...
999973  0.055052  0.985184  0.232803  0.132318  0.692209  4.195302
999984  0.410665  0.863263  0.498175  0.880650  0.946478  1.309999
999986  0.101766  0.844262  0.776608  0.139076  0.144501  1.168783
999991  0.213995  0.734381  0.502683  0.892457  0.642731  1.101309
999992  0.477495  0.976068  0.820444  0.290795  0.757657  1.446854

[149597 rows x 6 columns]

In [178]:
pd.eval('df[(df.A < 0.5) & (df.B > 0.7)]')

A         B         C         D         E         R
5       0.440921  0.838153  0.248619  0.202795  0.156731  3.780372
8       0.466091  0.993029  0.383327  0.956249  0.387757  2.685855
18      0.466075  0.805493  0.217403  0.552942  0.440928  3.927339
35      0.411488  0.706803  0.459651  0.805474  0.650193  1.425469
44      0.113028  0.903721  0.461744  0.981137  0.169687  1.903733
...          ...       ...       ...       ...       ...       ...
999973  0.055052  0.985184  0.232803  0.132318  0.692209  4.195302
999984  0.410665  0.863263  0.498175  0.880650  0.946478  1.309999
999986  0.101766  0.844262  0.776608  0.139076  0.144501  1.168783
999991  0.213995  0.734381  0.502683  0.892457  0.642731  1.101309
999992  0.477495  0.976068  0.820444  0.290795  0.757657  1.446854

[149597 rows x 6 columns]

In [307]:
df.query('(A<0.5) and (B>0.7)')

UndefinedVariableError: name 'A' is not defined

In [180]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E         R
1       0.045590  0.059767  0.321974  0.698530  0.134622  0.137180
16      0.097014  0.399170  0.164228  0.300632  0.431824  2.397773
19      0.295480  0.257788  0.119367  0.280885  0.377018  2.349202
20      0.170766  0.366148  0.417656  0.508937  0.506616  0.789605
21      0.160681  0.261311  0.971445  0.514154  0.549359  0.147217
...          ...       ...       ...       ...       ...       ...
999985  0.349805  0.113920  0.521640  0.084595  0.150734  0.555441
999988  0.004163  0.320284  0.762464  0.563928  0.556441  0.110434
999989  0.276544  0.132413  0.096026  0.458857  0.938140  1.225003
999993  0.131334  0.109570  0.472440  0.773434  0.810899 -0.263919
999994  0.041509  0.073871  0.243807  0.287956  0.761551  0.125208

[250177 rows x 6 columns]

In [181]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E         R
1       0.045590  0.059767  0.321974  0.698530  0.134622  0.137180
16      0.097014  0.399170  0.164228  0.300632  0.431824  2.397773
19      0.295480  0.257788  0.119367  0.280885  0.377018  2.349202
20      0.170766  0.366148  0.417656  0.508937  0.506616  0.789605
21      0.160681  0.261311  0.971445  0.514154  0.549359  0.147217
...          ...       ...       ...       ...       ...       ...
999985  0.349805  0.113920  0.521640  0.084595  0.150734  0.555441
999988  0.004163  0.320284  0.762464  0.563928  0.556441  0.110434
999989  0.276544  0.132413  0.096026  0.458857  0.938140  1.225003
999993  0.131334  0.109570  0.472440  0.773434  0.810899 -0.263919
999994  0.041509  0.073871  0.243807  0.287956  0.761551  0.125208

[250177 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [182]:
s1 = pd.Series(['a','b'], index = [1,2])
s1 = pd.Series(['c','d'], index = [3,4])
pd.concat([s1,s2])

3     c
4     d
1     2
2     4
3     6
4     8
5    10
dtype: object

In [183]:
def create_df(cols, idx):
    data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
    return pd.DataFrame(data, index = idx)

In [184]:
df1 = create_df('AB',[1,2])
df2 = create_df('AB',[3,4])
df1

A   B
1  a1  b1
2  a2  b2

In [185]:
df2

A   B
3  a3  b3
4  a4  b4

In [186]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [187]:
df3 = create_df('AB',[0,1])
df3

A   B
0  a0  b0
1  a1  b1

In [188]:
df4 = create_df('CD', [0,1])
df4

C   D
0  c0  d0
1  c1  d1

In [189]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [190]:
# pd.concat([df1 ,df3], verify_integrity = True)

In [191]:
pd.concat([df1, df3], ignore_index = True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [192]:
pd.concat([df1, df2], keys=['x','y'])

A   B
x 1  a1  b1
  2  a2  b2
y 3  a3  b3
  4  a4  b4

In [193]:
df5 = create_df('ABC', [1,2])
df6 = create_df('BCD', [3,4])
pd.concat([df5,df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [194]:
# 1:54:36
pd.concat([df5, df6], join='inner') # 모두 존재하는 데이터만 inner join 함

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [195]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [196]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [197]:
pd.concat([df1 ,df3, df4])

A    B    C    D
1   a1   b1  NaN  NaN
2   a2   b2  NaN  NaN
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

### 병합과 조인

In [198]:
df1 = pd.DataFrame({'학생':['솔이','박솔이','허솔이','이솔이'],
                    '학과' :['경영','회계','경제','영문']})
                          
df1

학생  학과
0   솔이  경영
1  박솔이  회계
2  허솔이  경제
3  이솔이  영문

In [199]:
df2 = pd.DataFrame({'학생':['솔이','박솔이','허솔이','이솔이'],
                    '입학년도' :[2013,2014,2015,2016]})
                          
df2

학생  입학년도
0   솔이  2013
1  박솔이  2014
2  허솔이  2015
3  이솔이  2016

In [200]:
df3 = pd.merge(df1 , df2)
df3

학생  학과  입학년도
0   솔이  경영  2013
1  박솔이  회계  2014
2  허솔이  경제  2015
3  이솔이  영문  2016

In [201]:
df4 = pd.DataFrame({'학과':['경영','회계','경제','영문'],
                   '학과장':['응','너','유','재']})

In [202]:
df4

학과 학과장
0  경영   응
1  회계   너
2  경제   유
3  영문   재

In [203]:
pd.merge(df3, df4)

학생  학과  입학년도 학과장
0   솔이  경영  2013   응
1  박솔이  회계  2014   너
2  허솔이  경제  2015   유
3  이솔이  영문  2016   재

In [204]:
df5 = pd.DataFrame({'학과':['경영','교육','교육','컴퓨터','컴퓨터','통계'],
                   '과목' : ['경영개론','기초수학','통계학','미시경제학','프로그래밍','알고리즘']})

In [205]:
pd.merge(df1, df2 , on = '학생')

학생  학과  입학년도
0   솔이  경영  2013
1  박솔이  회계  2014
2  허솔이  경제  2015
3  이솔이  영문  2016

In [206]:
df6 = pd.DataFrame({'이름':['솔이','박솔이','허솔이','이솔이'],
                   '성적':['A','B','C','D']})

In [207]:
pd.merge(df1, df6, left_on = '학생', right_on = '이름')

학생  학과   이름 성적
0   솔이  경영   솔이  A
1  박솔이  회계  박솔이  B
2  허솔이  경제  허솔이  C
3  이솔이  영문  이솔이  D

In [208]:
pd.merge(df1, df6, left_on = '학생', right_on = '이름').drop('이름', axis=1)

학생  학과 성적
0   솔이  경영  A
1  박솔이  회계  B
2  허솔이  경제  C
3  이솔이  영문  D

In [209]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [210]:
mdf1

학과
학생     
솔이   경영
박솔이  회계
허솔이  경제
이솔이  영문

In [211]:
mdf2

입학년도
학생       
솔이   2013
박솔이  2014
허솔이  2015
이솔이  2016

In [212]:
pd.merge(mdf1, mdf2, left_index = True, right_index = True)

학과  입학년도
학생           
솔이   경영  2013
박솔이  회계  2014
허솔이  경제  2015
이솔이  영문  2016

In [213]:
mdf1.join(mdf2)

학과  입학년도
학생           
솔이   경영  2013
박솔이  회계  2014
허솔이  경제  2015
이솔이  영문  2016

In [214]:
pd.merge(mdf1, df6, left_index = True, right_on ='이름')

학과   이름 성적
0  경영   솔이  A
1  회계  박솔이  B
2  경제  허솔이  C
3  영문  이솔이  D

In [215]:
df7 = pd.DataFrame({'이름':['솔이','박솔이','이솔이'],
                   '주문음식' : ['피자','햄버거','자장면']})
df7

이름 주문음식
0   솔이   피자
1  박솔이  햄버거
2  이솔이  자장면

In [216]:
df8 = pd.DataFrame({'이름':['솔이','박솔이','요솔이'],
                   '주문음료' : ['콜라','사이다','약콩']})
df8

이름 주문음료
0   솔이   콜라
1  박솔이  사이다
2  요솔이   약콩

In [217]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0   솔이   피자   콜라
1  박솔이  햄버거  사이다

In [218]:
pd.merge(df7, df8, how='outer')

이름 주문음식 주문음료
0   솔이   피자   콜라
1  박솔이  햄버거  사이다
2  이솔이  자장면  NaN
3  요솔이  NaN   약콩

In [219]:
pd.merge(df7, df8, how='left')

이름 주문음식 주문음료
0   솔이   피자   콜라
1  박솔이  햄버거  사이다
2  이솔이  자장면  NaN

In [220]:
pd.merge(df7, df8, how='right')

이름 주문음식 주문음료
0   솔이   피자   콜라
1  박솔이  햄버거  사이다
2  요솔이  NaN   약콩

In [221]:
df9 = pd.DataFrame({'이름':['솔이','박솔이','이솔이','정솔이'],
                   '순위':[4,1,3,2]})
df9

이름  순위
0   솔이   4
1  박솔이   1
2  이솔이   3
3  정솔이   2

In [222]:
df10 = pd.DataFrame({'이름':['솔이','박솔이','이솔이','정솔이'],
                   '순위':[1,2,3,4]})
df10

이름  순위
0   솔이   1
1  박솔이   2
2  이솔이   3
3  정솔이   4

In [223]:
pd.merge(df9,df10, on='이름')

이름  순위_x  순위_y
0   솔이     4     1
1  박솔이     1     2
2  이솔이     3     3
3  정솔이     2     4

In [224]:
pd.merge(df9,df10, on='이름', suffixes=['_인기','_성적'])

이름  순위_인기  순위_성적
0   솔이      4      1
1  박솔이      1      2
2  이솔이      3      3
3  정솔이      2      4

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation) 2:15


In [225]:
df = pd.DataFrame([[1,1.2,np.nan],
                 [2.4,5.5,4.2],
                 [np.nan,np.nan,np.nan],
                 [0.44 , -3.1, -4.1]],
                 index = [1,2,3,4],
                 columns = ['A','B','C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [226]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [227]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [228]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [229]:
print(df)
print(np.argmin(df), np.argmax(df))

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
2 2


In [230]:
print(df)
print(df.idxmin())
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [231]:
print(df)
print(df.std())
print(df.var())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [232]:
print(df)
print(df.skew())
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [233]:
print(df)
print(df.sum())
print(df.cumsum())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [234]:
print(df)
print(df.prod())
print(df.cumprod())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [235]:
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [236]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [237]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [238]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [239]:
df.corrwith(df.B) # B를 기준으로 correlation

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [240]:
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [241]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [242]:
df['A'].value_counts()

0.44    1
2.40    1
1.00    1
Name: A, dtype: int64

### GroupBy 연산

In [243]:
df = pd.DataFrame({'c1':['a','a','b','b','c','d','d'],
                  'c2': ['A','B','B','A','D','C','C'],
                  'c3':np.random.randint(7),
                  'c4': np.random.randint(7)})
df

c1 c2  c3  c4
0  a  A   2   2
1  a  B   2   2
2  b  B   2   2
3  b  A   2   2
4  c  D   2   2
5  d  C   2   2
6  d  C   2   2

In [244]:
df.dtypes

c1    object
c2    object
c3     int64
c4     int64
dtype: object

In [245]:
df['c3'].groupby(df['c1']).mean()

c1
a    2
b    2
c    2
d    2
Name: c3, dtype: int64

In [246]:
df['c4'].groupby(df['c2']).std()

c2
A    0.0
B    0.0
C    0.0
D    NaN
Name: c4, dtype: float64

In [247]:
df['c4'].groupby([df['c1'],df['c2']]).mean()

c1  c2
a   A     2
    B     2
b   A     2
    B     2
c   D     2
d   C     2
Name: c4, dtype: int64

In [248]:
df.groupby('c1').mean()

c3  c4
c1        
a    2   2
b    2   2
c    2   2
d    2   2

In [249]:
df.groupby(['c1','c2']).mean()

c3  c4
c1 c2        
a  A    2   2
   B    2   2
b  A    2   2
   B    2   2
c  D    2   2
d  C    2   2

In [250]:
df.groupby(['c1','c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
c   D     1
d   C     2
dtype: int64

In [251]:
for c1, group in df.groupby('c1'):
    print(c1)
    print(group)

a
  c1 c2  c3  c4
0  a  A   2   2
1  a  B   2   2
b
  c1 c2  c3  c4
2  b  B   2   2
3  b  A   2   2
c
  c1 c2  c3  c4
4  c  D   2   2
d
  c1 c2  c3  c4
5  d  C   2   2
6  d  C   2   2


In [252]:
df.groupby(['c1','c2']).mean()

c3  c4
c1 c2        
a  A    2   2
   B    2   2
b  A    2   2
   B    2   2
c  D    2   2
d  C    2   2

In [253]:
for (c1, c2) in df.groupby(['c1','c2']):
    print((c1, c2))
    print(group)

(('a', 'A'),   c1 c2  c3  c4
0  a  A   2   2)
  c1 c2  c3  c4
5  d  C   2   2
6  d  C   2   2
(('a', 'B'),   c1 c2  c3  c4
1  a  B   2   2)
  c1 c2  c3  c4
5  d  C   2   2
6  d  C   2   2
(('b', 'A'),   c1 c2  c3  c4
3  b  A   2   2)
  c1 c2  c3  c4
5  d  C   2   2
6  d  C   2   2
(('b', 'B'),   c1 c2  c3  c4
2  b  B   2   2)
  c1 c2  c3  c4
5  d  C   2   2
6  d  C   2   2
(('c', 'D'),   c1 c2  c3  c4
4  c  D   2   2)
  c1 c2  c3  c4
5  d  C   2   2
6  d  C   2   2
(('d', 'C'),   c1 c2  c3  c4
5  d  C   2   2
6  d  C   2   2)
  c1 c2  c3  c4
5  d  C   2   2
6  d  C   2   2


In [254]:
df.groupby(['c1','c2'])['c4'].mean()

c1  c2
a   A     2
    B     2
b   A     2
    B     2
c   D     2
d   C     2
Name: c4, dtype: int64

In [255]:
df.groupby('c1')['c3'].quantile()

c1
a    2.0
b    2.0
c    2.0
d    2.0
Name: c3, dtype: float64

In [256]:
df.groupby('c1')['c3'].count()

c1
a    2
b    2
c    1
d    2
Name: c3, dtype: int64

In [257]:
df.groupby('c1')['c3'].median()

c1
a    2
b    2
c    2
d    2
Name: c3, dtype: int64

In [258]:
df.groupby(['c1','c2'])['c4'].agg(['mean','max','min'])

mean  max  min
c1 c2                
a  A      2    2    2
   B      2    2    2
b  A      2    2    2
   B      2    2    2
c  D      2    2    2
d  C      2    2    2

In [259]:
df.groupby(['c1','c2'], as_index=False)['c4'].mean()

c1 c2  c4
0  a  A   2
1  a  B   2
2  b  A   2
3  b  B   2
4  c  D   2
5  d  C   2

In [260]:
df.groupby(['c1','c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     2
    B     2
b   A     2
    B     2
c   D     2
d   C     2
Name: c4, dtype: int64

In [261]:
def top(df, n=3, column = 'c1'):
    return df.sort_values(by=column)[-n:]

top(df, n=5)

c1 c2  c3  c4
2  b  B   2   2
3  b  A   2   2
4  c  D   2   2
5  d  C   2   2
6  d  C   2   2

In [262]:
df.groupby('c1').apply(top)

c1 c2  c3  c4
c1                
a  0  a  A   2   2
   1  a  B   2   2
b  2  b  B   2   2
   3  b  A   2   2
c  4  c  D   2   2
d  5  d  C   2   2
   6  d  C   2   2

### 피벗 테이블(Pivot Table)


In [263]:
df.pivot_table(['c3','c4'],
              index = ['c1'],
              columns=['c2'])

c3                  c4               
c2    A    B    C    D    A    B    C    D
c1                                        
a   2.0  2.0  NaN  NaN  2.0  2.0  NaN  NaN
b   2.0  2.0  NaN  NaN  2.0  2.0  NaN  NaN
c   NaN  NaN  NaN  2.0  NaN  NaN  NaN  2.0
d   NaN  NaN  2.0  NaN  NaN  NaN  2.0  NaN

In [264]:
df.pivot_table(['c3','c4'],
              index = ['c1'],
              columns=['c2'],
              margins=True) # all 이 출력됨 총합 평균

c3                      c4                   
c2     A    B    C    D All    A    B    C    D All
c1                                                 
a    2.0  2.0  NaN  NaN   2  2.0  2.0  NaN  NaN   2
b    2.0  2.0  NaN  NaN   2  2.0  2.0  NaN  NaN   2
c    NaN  NaN  NaN  2.0   2  NaN  NaN  NaN  2.0   2
d    NaN  NaN  2.0  NaN   2  NaN  NaN  2.0  NaN   2
All  2.0  2.0  2.0  2.0   2  2.0  2.0  2.0  2.0   2

In [265]:
df.pivot_table(['c3','c4'],
              index = ['c1'],
              columns=['c2'],
              margins=True,
              aggfunc=sum)

c3                      c4                   
c2     A    B    C    D All    A    B    C    D All
c1                                                 
a    2.0  2.0  NaN  NaN   4  2.0  2.0  NaN  NaN   4
b    2.0  2.0  NaN  NaN   4  2.0  2.0  NaN  NaN   4
c    NaN  NaN  NaN  2.0   2  NaN  NaN  NaN  2.0   2
d    NaN  NaN  4.0  NaN   4  NaN  NaN  4.0  NaN   4
All  4.0  4.0  4.0  2.0  14  4.0  4.0  4.0  2.0  14

In [266]:
df.pivot_table(['c3','c4'],
              index = ['c1'],
              columns=['c2'],
              margins=True,
              aggfunc=sum,
              fill_value = 0)

c3              c4             
c2   A  B  C  D All  A  B  C  D All
c1                                 
a    2  2  0  0   4  2  2  0  0   4
b    2  2  0  0   4  2  2  0  0   4
c    0  0  0  2   2  0  0  0  2   2
d    0  0  4  0   4  0  0  4  0   4
All  4  4  4  2  14  4  4  4  2  14

In [267]:
pd.crosstab(df.c1 ,df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  0  0
c   0  0  0  1
d   0  0  2  0

In [268]:
pd.crosstab(df.c1, df.c2, values=df.c3 , aggfunc = sum, margins = True)

c2     A    B    C    D  All
c1                          
a    2.0  2.0  NaN  NaN    4
b    2.0  2.0  NaN  NaN    4
c    NaN  NaN  NaN  2.0    2
d    NaN  NaN  4.0  NaN    4
All  4.0  4.0  4.0  2.0   14

### 범주형(Categorical) 데이터


In [269]:
s = pd.Series(['c1','c2','c1','c2','c1'] * 2)
s

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
dtype: object

In [270]:
s.unique()

array(['c1', 'c2'], dtype=object)

In [271]:
s.value_counts()

c1    6
c2    4
dtype: int64

In [272]:
code = pd.Series([0,1,0,1,0,1]*2)
code

0     0
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
dtype: int64

In [273]:
d= pd.Series(['c1','c2'])

In [274]:
# 범주형에 특정 코드를 붙여서 계산에 코드를 사용
d.take(code)

0    c1
1    c2
0    c1
1    c2
0    c1
1    c2
0    c1
1    c2
0    c1
1    c2
0    c1
1    c2
dtype: object

In [275]:
df = pd.DataFrame({'id':np.arange(len(s)),
                   'c':s,
                   'v':np.random.randint(1000,5000, size=len(s))})
df


id   c     v
0   0  c1  2141
1   1  c2  2308
2   2  c1  2940
3   3  c2  3992
4   4  c1  3179
5   5  c1  3232
6   6  c2  2795
7   7  c1  4841
8   8  c2  1250
9   9  c1  3830

In [276]:
c = df['c'].astype('category')
c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [277]:
c.values

['c1', 'c2', 'c1', 'c2', 'c1', 'c1', 'c2', 'c1', 'c2', 'c1']
Categories (2, object): ['c1', 'c2']

In [278]:
c.values.categories

Index(['c1', 'c2'], dtype='object')

In [279]:
c.values.codes

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [280]:
df['c'] = c
df.c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [281]:
c = pd.Categorical(['c1','c2','c3','c1','c2'])
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [282]:
categories = ['c1','c2','c3']
codes = [0,1,2,0,1]
c = pd.Categorical.from_codes(codes, categories)
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [283]:
pd.Categorical.from_codes(codes, categories, ordered=True)

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [284]:
c.as_ordered()

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [285]:
c.codes

array([0, 1, 2, 0, 1], dtype=int8)

In [286]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

In [287]:
c = c.set_categories(['c1','c2','c3','c4','c5'])
c.categories

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')

In [288]:
c.value_counts()

c1    2
c2    2
c3    1
c4    0
c5    0
dtype: int64

In [289]:
c[c.isin(['c1','c3'])]

['c1', 'c3', 'c1']
Categories (5, object): ['c1', 'c2', 'c3', 'c4', 'c5']

In [290]:
c= c.remove_unused_categories()

In [291]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly