# Pandas 한번에 제대로 배우기




---



In [22]:
import pandas as pd
import numpy as np

## Pandas 객체


### Series 객체

In [6]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
             index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [7]:
s['a']

0.0

In [8]:
s['c']

0.5

In [9]:
'b' in s

True

In [10]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
             index = ['2','4','6','8','10'])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [11]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [12]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [15]:
s.isin([0.25, 0.75])

4    0.25
8    0.75
dtype: float64

In [18]:
pop_tuple = {'서울특별시':9720846,
            '부산광역시':3404423,
            '인천광역시':2947217,
            '대구광역시':2427954,
            '대전광역시':1471040,
            '광주광역시':1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [19]:
population['서울특별시']

9720846

In [20]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [21]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4,'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [24]:
pd.DataFrame(np.random.rand(5,5),
            columns = ['A','B','C','D','E'],
             index = [1,2,3,4,5])

A         B         C         D         E
1  0.756085  0.120968  0.282661  0.937097  0.905849
2  0.430076  0.075888  0.433609  0.622432  0.782790
3  0.879458  0.221025  0.006592  0.480356  0.197165
4  0.752423  0.217967  0.317030  0.749423  0.018154
5  0.863209  0.583961  0.935327  0.163480  0.059563

In [25]:
male_tuple = {'서울특별시':720846,
            '부산광역시':404423,
            '인천광역시':947217,
            '대구광역시':427954,
            '대전광역시':471040,
            '광주광역시':455048}
male = pd.Series(male_tuple)
male

서울특별시    720846
부산광역시    404423
인천광역시    947217
대구광역시    427954
대전광역시    471040
광주광역시    455048
dtype: int64

In [26]:
female_tuple = {'서울특별시':1720846,
            '부산광역시':1404423,
            '인천광역시':1947217,
            '대구광역시':4227954,
            '대전광역시':1471040,
            '광주광역시':1455048}
female = pd.Series(female_tuple)
female

서울특별시    1720846
부산광역시    1404423
인천광역시    1947217
대구광역시    4227954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [29]:
korea_df = pd.DataFrame({'인구수':population,
              '남자인구수':male,
              '여자인구수':female})

In [30]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [31]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [33]:
korea_df['여자인구수']

서울특별시    1720846
부산광역시    1404423
인천광역시    1947217
대구광역시    4227954
대전광역시    1471040
광주광역시    1455048
Name: 여자인구수, dtype: int64

### Index 객체


In [35]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [36]:
idx[1]

4

In [39]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [40]:
idx[-1::]

Int64Index([10], dtype='int64')

In [41]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [43]:
print(idx)
print(idx.size)
print(idx.ndim)
print(idx.shape)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
1
(5,)
int64


#### Index 연산

In [50]:
idx1 = pd.Index([1,2,3,4,5])
idx2 = pd.Index([4,5,6,7,8])

print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2 )
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2) # 공통 뺀 나머지 여집합.


Int64Index([1, 2, 3, 4, 5, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 3], dtype='int64')
Int64Index([-3, -3, -3, -3, -3], dtype='int64')
Int64Index([4, 5], dtype='int64')
Int64Index([4, 5], dtype='int64')
Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 3, 4, 5], dtype='int64')
Int64Index([2, 3, 4, 5], dtype='int64')
Int64Index([1, 2, 3, 6, 7, 8], dtype='int64')


## 인덱싱(Indexing)

In [53]:
s = pd.Series([0, 0.25 , 0.5 , 0.75 , 1.0],
             index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [54]:
s['b']

0.25

In [55]:
'b' in s

True

In [56]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [58]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [59]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [60]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [61]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [62]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [63]:
s[['a','c','d']]

a    0.00
c    0.50
d    0.75
dtype: float64

### Series 인덱싱

In [66]:
s = pd.Series(['a','b','c','d','e'],
             index = [1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [69]:
s[1]

'a'

In [70]:
s[2:4]

5    c
7    d
dtype: object

In [71]:
s.iloc[1]

'b'

In [72]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [73]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [74]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [77]:
korea_df

인구수   남자인구수    여자인구수
서울특별시  9720846  720846  1720846
부산광역시  3404423  404423  1404423
인천광역시  2947217  947217  1947217
대구광역시  2427954  427954  4227954
대전광역시  1471040  471040  1471040
광주광역시  1455048  455048  1455048

In [79]:
korea_df['남자인구수']

서울특별시    720846
부산광역시    404423
인천광역시    947217
대구광역시    427954
대전광역시    471040
광주광역시    455048
Name: 남자인구수, dtype: int64

In [80]:
korea_df.남자인구수

서울특별시    720846
부산광역시    404423
인천광역시    947217
대구광역시    427954
대전광역시    471040
광주광역시    455048
Name: 남자인구수, dtype: int64

In [81]:
korea_df.여자인구수

서울특별시    1720846
부산광역시    1404423
인천광역시    1947217
대구광역시    4227954
대전광역시    1471040
광주광역시    1455048
Name: 여자인구수, dtype: int64

In [82]:
korea_df['남녀비율'] = (korea_df.남자인구수*100 / korea_df.여자인구수)

In [83]:
korea_df

인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  1720846  41.889048
부산광역시  3404423  404423  1404423  28.796381
인천광역시  2947217  947217  1947217  48.644655
대구광역시  2427954  427954  4227954  10.122012
대전광역시  1471040  471040  1471040  32.020883
광주광역시  1455048  455048  1455048  31.273745

In [84]:
korea_df.values

array([[9.72084600e+06, 7.20846000e+05, 1.72084600e+06, 4.18890476e+01],
       [3.40442300e+06, 4.04423000e+05, 1.40442300e+06, 2.87963811e+01],
       [2.94721700e+06, 9.47217000e+05, 1.94721700e+06, 4.86446554e+01],
       [2.42795400e+06, 4.27954000e+05, 4.22795400e+06, 1.01220117e+01],
       [1.47104000e+06, 4.71040000e+05, 1.47104000e+06, 3.20208832e+01],
       [1.45504800e+06, 4.55048000e+05, 1.45504800e+06, 3.12737449e+01]])

In [85]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  7.208460e+05  4.044230e+05  9.472170e+05  4.279540e+05  4.710400e+05   
여자인구수  1.720846e+06  1.404423e+06  1.947217e+06  4.227954e+06  1.471040e+06   
남녀비율   4.188905e+01  2.879638e+01  4.864466e+01  1.012201e+01  3.202088e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  4.550480e+05  
여자인구수  1.455048e+06  
남녀비율   3.127374e+01

In [86]:
korea_df.values[0] # 서울특별시만

array([9.72084600e+06, 7.20846000e+05, 1.72084600e+06, 4.18890476e+01])

In [87]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [88]:
korea_df.loc[:'인천광역시',:'남자인구수']

인구수   남자인구수
서울특별시  9720846  720846
부산광역시  3404423  404423
인천광역시  2947217  947217

In [89]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  1720846  41.889048
부산광역시  3404423  404423  1404423  28.796381
인천광역시  2947217  947217  1947217  48.644655
대구광역시  2427954  427954  4227954  10.122012
대전광역시  1471040  471040  1471040  32.020883
광주광역시  1455048  455048  1455048  31.273745

In [91]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수    여자인구수       남녀비율
대전광역시  1471040  471040  1471040  32.020883
광주광역시  1455048  455048  1455048  31.273745

In [92]:
korea_df.loc[(korea_df.인구수 >= 2500000)]

인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  1720846  41.889048
부산광역시  3404423  404423  1404423  28.796381
인천광역시  2947217  947217  1947217  48.644655

In [94]:
korea_df.loc[korea_df.남녀비율>100]

Empty DataFrame
Columns: [인구수, 남자인구수, 여자인구수, 남녀비율]
Index: []

In [95]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남녀비율 < 100)]

인구수   남자인구수    여자인구수       남녀비율
서울특별시  9720846  720846  1720846  41.889048
부산광역시  3404423  404423  1404423  28.796381
인천광역시  2947217  947217  1947217  48.644655

In [97]:
korea_df.iloc[:3,:2]

인구수   남자인구수
서울특별시  9720846  720846
부산광역시  3404423  404423
인천광역시  2947217  947217

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [99]:
idx_tuples = [('서울특별시', 2010), ('서울특별시',2020),
             ('부산광역시', 2010), ('부산광역시',2020),
             ('인천광역시', 2010), ('인천광역시',2020),
             ('대구광역시', 2010), ('대구광역시',2020),
             ('대전광역시', 2010), ('대전광역시',2020),
             ('광주광역시', 2010), ('광주광역시',2020),]

In [100]:
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [103]:
pop_tuples = [10312545, 9720846,
             2567910, 3404423,
             2758296, 2947217,
             2511676, 2427954,
             1503664, 1471040,
             1454636, 1455048]
population = pd.Series(pop_tuples, index = idx_tuples)

In [104]:
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [105]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [106]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [107]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [108]:
population['대전광역시',:]

2010    1503664
2020    1471040
dtype: int64

In [109]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [110]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [ ]:
male_tuple = [] # 50:32 https://www.youtube.com/watch?v=lG8pEwvYwCw&t=1288s

#### 다중 인덱스 생성

#### 인덱싱 및 슬라이싱

#### 다중 인덱스 재정렬

## 데이터 연산

### 연산자 범용 함수


#### add()

#### sub() / subtract()

#### mul() / multply()




#### truediv() /  div() / divide() / floordiv()

#### mod()

#### pow()

### 정렬(Sort)

### 순위(Ranking)


### 고성능 연산

## 데이터 결합

### Concat() / Append()

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly